---
title: "Capstone Proposal - Energy Efficiency Analysis"
author: "Terence Fernandez"
date: "July 16, 2017"
output: html_document
---

This R Markdown document presents a brief proposal of the Energy Efficiency Analysis:


Project Name: Energy Efficiency Analysis

Data Set Source: UCI Machine Learning Repository


Project Abstract:

This project is an analysis of an Energy Efficiency Data Set whereby it contains heating and Loading requirements of energy-efficient buildings as a function of building parameters. 

Reasons for selecting this data set:

1) Relevant data although collected in 2012.
2) Multivariate Data characteristics.
3) Able to perform both classification or regression analysis.

Data Set information:

The Energy Efficienfy Data set uses 12 different building shapes to assess heating and cooling loads in energy-efficient building structures. The buildings differ with respect to attributes such as glazing area, the glazing area distribution, and the orientation, amongst other parameters. The data set simulates various settings as functions of 8 attributes (x1 to x8) resulting in 768 samples and two real valued responses which are heating and cooling load (y1 and y2). 

X1 - Relative Compactness, 
X2 - Surface Area, 
X3 - Wall Area, 
X4 - Roof Area, 
X5 - Overall Height, 
X6 - Orientation, 
X7 - Glazing Area, 
X8 - Glazing Area Distribution, 
y1 - Heating Load, 
y2 - Cooling Load,

Project Statement:

The goal is to apply a Support Vector Machine (SVM) to perform classification, come up with a prediction model and be able to tune that model. 

SVM is a supervised machine learning algorithm which can be used for both classification or regression. However often used in classification especially where the dataset is not complexed. 

Project Deliverables:

1) Process and methodology.
2) Prediction Data.
3) A tuned model and evaluation.
4) A report containing all of the above and R code.